import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from "@/components/header/header";
import Menu from "@/components/menu/menu";
import Banner from "@/components/banner/banner";
import Info from "@/components/info/info";
import Price from "@/components/price/price";
import Footer from "@/components/footer/footer";
import Contact from "@/components/contact/contact";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
          <Menu />
          <Banner />
          <Info />
          <Price />
          <Contact />
        <Footer />
      </main>
    </>
  )
}
